# First exploration (Mathis)

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import os

In [3]:
candidate_info = pd.read_csv('data/archelect_search.csv')

C:\Users\mathi\AppData\Local\Temp\ipykernel_26412\2336569437.py:1: DtypeWarning: Columns (8,9,10,12,28,29,30,31,32,33,34,35,36,37,38,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  candidate_info = pd.read_csv('data/archelect_search.csv')

In [9]:
text_extracted_1981 = pd.DataFrame(columns=['id', 'text'])
files = os.listdir('data/legislatives_1981')
for file in files:
    with open('data/legislatives_1981/' + file, encoding="utf-8") as f:
        text = f.read()
    text_extracted_1981 = pd.concat([text_extracted_1981, pd.DataFrame([[file.replace('.txt', ''), text]], columns=['id','text'])])
text_extracted_1981 = pd.merge(text_extracted_1981, candidate_info, how='inner')
text_extracted_1981.head()

,id,text,date,subject,title,contexte-election,contexte-tour,cote,departement,departement-nom,...,suppleant-age-calcule,suppleant-age-tranche,suppleant-profession,suppleant-mandat-en-cours,suppleant-mandat-passe,suppleant-associations,suppleant-autres-statuts,suppleant-soutien,suppleant-liste,suppleant-decorations
0,EL134_L_1981_06_001_01_1_PF_01,ELECTIONS LEGISLATIVES - 14 JUIN 1981 AIN 1e C...,1981-06-14,France;Assemblée Nationale;Ve République;Élect...,"Élections législatives de 1981, Ain - 01, circ...",législatives,1,EL134,01,Ain,...,non mentionné,non mentionné,infirmière,non mentionné,non mentionné,syndicat,non mentionné,Parti socialiste unifié,non mentionné,non
1,EL134_L_1981_06_001_01_1_PF_02,Sciences Po / fonds CEVIPOF\nELECTIONS LÉGISLA...,1981-06-14,Élections législatives;Ve République;Assemblée...,"Élections législatives de 1981, Ain - 01, circ...",législatives,1,EL134,01,Ain,...,non mentionné,non mentionné,non mentionné,maire-adjoint,non mentionné,syndicat,non mentionné,Parti communiste français,Union de la gauche,non
2,EL134_L_1981_06_001_01_1_PF_03,Sciences Po / fonds CEVIPOF\nRÉPUBLIQUE FRANÇA...,1981-06-14,Élections législatives;Ve République;France;As...,"Élections législatives de 1981, Ain - 01, circ...",législatives,1,EL134,01,Ain,...,non mentionné,non mentionné,docteur,non mentionné,non mentionné,non mentionné,non mentionné,Parti socialiste;Mouvement des radicaux de gauche,non mentionné,non
3,EL134_L_1981_06_001_01_1_PF_04,REPUBLIQUE FRANÇAISE - ELECTIONS LEGISLATIVES ...,1981-06-14,Assemblée Nationale;France;Ve République;Élect...,"Élections législatives de 1981, Ain - 01, circ...",législatives,1,EL134,01,Ain,...,non mentionné,non mentionné,commerçant,non mentionné,non mentionné,culture;politique,non mentionné,Fédération des socialistes démocrates,non mentionné,non
4,EL134_L_1981_06_001_01_1_PF_05,REPUBLIQUE FRANÇAISE - PREMIERE CIRCONSCRIPTIO...,1981-06-14,Assemblée Nationale;Élections législatives;Ve ...,"Élections législatives de 1981, Ain - 01, circ...",législatives,1,EL134,01,Ain,...,56,entre 50 et 59 ans,chirurgien,non mentionné,député suppléant,professionnel,non mentionné,Rassemblement pour la République;Union pour la...,Union pour la nouvelle majorité,non

In [27]:
text_extracted_1981 = text_extracted_1981[['id', 'text', 'date', 'contexte-election',
       'contexte-tour', 'cote', 'departement',
       'departement-insee', 'identifiant de circonscription', 'titulaire-sexe',
       'titulaire-profession', 'titulaire-mandat-en-cours',
       'titulaire-mandat-passe', 'titulaire-associations',
       'titulaire-autres-statuts', 'titulaire-soutien', 'titulaire-liste',
       'titulaire-decorations']]
text_extracted_1981.head()
# text_extracted_1981['title'].value_counts()

,id,text,date,contexte-election,contexte-tour,cote,departement,departement-insee,identifiant de circonscription,titulaire-sexe,titulaire-profession,titulaire-mandat-en-cours,titulaire-mandat-passe,titulaire-associations,titulaire-autres-statuts,titulaire-soutien,titulaire-liste,titulaire-decorations
0,EL134_L_1981_06_001_01_1_PF_01,ELECTIONS LEGISLATIVES - 14 JUIN 1981 AIN 1e C...,1981-06-14,législatives,1,EL134,01,01 - Ain,1,femme,assistance sociale,maire-adjoint,non mentionné,non mentionné,non mentionné,Parti socialiste unifié,non mentionné,non
1,EL134_L_1981_06_001_01_1_PF_02,Sciences Po / fonds CEVIPOF\nELECTIONS LÉGISLA...,1981-06-14,législatives,1,EL134,01,01 - Ain,1,homme,non mentionné,maire-adjoint;conseiller régional,non mentionné,syndicat,non mentionné,Parti communiste français,Union de la gauche,non
2,EL134_L_1981_06_001_01_1_PF_03,Sciences Po / fonds CEVIPOF\nRÉPUBLIQUE FRANÇA...,1981-06-14,législatives,1,EL134,01,01 - Ain,1,homme,non mentionné,non mentionné,non mentionné,groupes de pression,non mentionné,Parti socialiste;Mouvement des radicaux de gauche,non mentionné,non
3,EL134_L_1981_06_001_01_1_PF_04,REPUBLIQUE FRANÇAISE - ELECTIONS LEGISLATIVES ...,1981-06-14,législatives,1,EL134,01,01 - Ain,1,homme,conducteur poids lourds,non mentionné,non mentionné,socio-caritatif;politique,réserve,Fédération des socialistes démocrates,non mentionné,non
4,EL134_L_1981_06_001_01_1_PF_05,REPUBLIQUE FRANÇAISE - PREMIERE CIRCONSCRIPTIO...,1981-06-14,législatives,1,EL134,01,01 - Ain,1,homme,non mentionné,conseiller régional;maire;conseiller général,député,non mentionné,réserve,Rassemblement pour la République;Union pour la...,Union pour la nouvelle majorité,oui